import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from 'sonner';
import Link from 'next/link';

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={outfit.className}>
        <ConvexClientProvider>
          <Header />
          {children}
          <Toaster richColors position="bottom-right" />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
